version: 2.1

jobs:
  prod-deployment:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "I'm going to run some deployments!"
      - when:
          condition: [ main, << pipeline.git.branch >> ]
          steps:
            - run: echo "This is my prod deployment!"
      - run: echo "prod-deployment job envoked"
  
  preprod-deployment:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "some preprod deployments - success!"
      - run: echo "This is my dev deployment!"


workflows:
  deployment-workflows:
    jobs:
      - prod-deployment
      - preprod-deployment